#!/bin/bash

export DEBUG=${DEBUG:-0}

export WALM_ENV_CONFIG=${WALM_ENV_CONFIG:-"production"}

export WALM_HOME=${WALM_HOME:-"/usr/lib/walm"}
export WALM_LOG_DIR=${WALM_LOG_DIR:-"/var/log/walm"}

export WALM_MYSQL_SERVER=${WALM_MYSQL_SERVER:-"localhost"}
export WALM_MYSQL_PORT=${WALM_MYSQL_PORT:-"3306"}
export WALM_MYSQL_USERNAME=${WALM_MYSQL_USERNAME:-"root"}
export WALM_MYSQL_PASSWORD=${WALM_MYSQL_PASSWORD:-"password"}
export WALM_DATABASE=${WALM_DATABASE:-"walmdb"}
export SQLALCHEMY_DATABASE_URI=mysql://${WALM_MYSQL_USERNAME}:${WALM_MYSQL_PASSWORD}@${WALM_MYSQL_SERVER}:${WALM_MYSQL_PORT}/${WALM_DATABASE}?charset=utf8

export WALM_WEBSERVER_ADDRESS=${WALM_WEBSERVER_ADDRESS:-"0.0.0.0"}
export WALM_WEBSERVER_PORT=${WALM_WEBSERVER_PORT:-"6180"}
export WALM_WORKERS=${WALM_WORKERS:-"5"}
export WALM_WEBSERVER_TIMEOUT=${WALM_WEBSERVER_TIMEOUT:-"60"}

export PRODUCT_META_HOME=${PRODUCT_META_HOME:-"/usr/lib/walm/product-meta"}

export KUBERNETES_HOST=${KUBERNETES_HOST:-"http://localhost:8080"}
export KUBERNETES_CLIENT_CERT=${KUBERNETES_CLIENT_CERT:-""}
export KUBERNETES_CLIENT_KEY=${KUBERNETES_CLIENT_KEY:-""}
export KUBERNETES_CA=${KUBERNETES_CA:-""}
