/*
 * walm
 *
 * warp application lifecycle manager
 *
 * API version: 1.0.0
 * Contact: bing.han@transwarp.io
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package ex

import (
	"fmt"
)

type ApiResponse struct {
	Code    int    `json:"code,omitempty" description:"code of the response"`
	Message string `json:"message,omitempty" description:"message of the response"`
}

func ReturnBadRequest() (int, ApiResponse) {
	ar := ApiResponse{
		Code:    INVALID_PARAMS,
		Message: fmt.Sprintf("%s", GetMsg(INVALID_PARAMS)),
	}
	return INVALID_PARAMS, ar
}

func ReturnInternalServerError(err error) (int, ApiResponse) {
	ar := ApiResponse{
		Code:    INTERNAL_ERROR,
		Message: fmt.Sprintf("%s:%s", GetMsg(INTERNAL_ERROR), err),
	}
	return INTERNAL_ERROR, ar
}

func ReturnClusterExistError() (int, ApiResponse) {
	ar := ApiResponse{
		Code:    ERROR_CLUSTER_EXIST,
		Message: fmt.Sprintf("%s", GetMsg(ERROR_CLUSTER_EXIST)),
	}
	return ERROR_CLUSTER_EXIST, ar
}

func ReturnClusterNotExistError() (int, ApiResponse) {
	ar := ApiResponse{
		Code:    ERROR_CLUSTER_NOT_EXIST,
		Message: fmt.Sprintf("%s", GetMsg(ERROR_CLUSTER_NOT_EXIST)),
	}
	return ERROR_CLUSTER_NOT_EXIST, ar
}

func ReturnOK() (int, ApiResponse) {
	ar := ApiResponse{
		Code:    SUCCESS,
		Message: GetMsg(SUCCESS),
	}
	return SUCCESS, ar
}
