// Code generated by mockery v1.0.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// Kafka is an autogenerated mock type for the Kafka type
type Kafka struct {
	mock.Mock
}

// SyncSendMessage provides a mock function with given fields: topic, message
func (_m *Kafka) SyncSendMessage(topic string, message string) error {
	ret := _m.Called(topic, message)

	var r0 error
	if rf, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = rf(topic, message)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
