// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag at
// 2018-07-23 12:34:34.722768407 +0800 CST m=+1.063560119

package docs

import (
	"github.com/swaggo/swag"
)

var doc = `{
    "swagger": "2.0",
    "info": {
        "description": "cluster lifecycle manager",
        "title": "Walm",
        "contact": {
            "name": "bing.han",
            "url": "http://transwarp.io",
            "email": "bing.han@transwarp.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "1.0.0"
    },
    "basePath": "/walm/api/v1",
    "paths": {
        "/cluster/namespace/{namespace}/name/{name}": {
            "get": {
                "description": "Get states of an Cluster",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Cluster"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "identifier of the namespace",
                        "name": "namespace",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "the name of cluster",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/helm.ReleaseInfo"
                            }
                        }
                    },
                    "400": {
                        "description": "Invalid Name supplied!",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/ex.ApiResponse"
                        }
                    },
                    "404": {
                        "description": "cluster not found",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/ex.ApiResponse"
                        }
                    },
                    "500": {
                        "description": "Server Error",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/ex.ApiResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Deploy an Cluster",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Cluster"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "identifier of the namespace",
                        "name": "namespace",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "the name of cluster",
                        "name": "name",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Apps of Cluster",
                        "name": "apps",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/cluster.Cluster"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/ex.ApiResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid Name supplied!",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/ex.ApiResponse"
                        }
                    },
                    "404": {
                        "description": "namespace not found",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/ex.ApiResponse"
                        }
                    },
                    "500": {
                        "description": "Server Error",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/ex.ApiResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete an Cluster",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Cluster"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "identifier of the namespace",
                        "name": "namespace",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "the name of cluster",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/ex.ApiResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid Name supplied!",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/ex.ApiResponse"
                        }
                    },
                    "404": {
                        "description": "cluster not found",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/ex.ApiResponse"
                        }
                    },
                    "500": {
                        "description": "Server Error",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/ex.ApiResponse"
                        }
                    }
                }
            }
        },
        "/cluster/namespace/{namespace}/name/{name}/instance": {
            "post": {
                "description": "Deploy an Instance into Cluster",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Cluster"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "identifier of the namespace",
                        "name": "namespace",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "the name of cluster",
                        "name": "name",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Apps of Cluster",
                        "name": "apps",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/helm.ReleaseRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/ex.ApiResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid Name supplied!",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/ex.ApiResponse"
                        }
                    },
                    "404": {
                        "description": "namespace not found",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/ex.ApiResponse"
                        }
                    },
                    "500": {
                        "description": "Server Error",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/ex.ApiResponse"
                        }
                    }
                }
            }
        },
        "/cluster/namespace/{namespace}/name/{name}/list": {
            "post": {
                "description": "Deploy an Instance list into Cluster",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Cluster"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "identifier of the namespace",
                        "name": "namespace",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "the name of cluster",
                        "name": "name",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Apps list of Cluster",
                        "name": "apps",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/cluster.ReleaseList"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/ex.ApiResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid Name supplied!",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/ex.ApiResponse"
                        }
                    },
                    "404": {
                        "description": "namespace not found",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/ex.ApiResponse"
                        }
                    },
                    "500": {
                        "description": "Server Error",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/ex.ApiResponse"
                        }
                    }
                }
            }
        },
        "/instance/namespace/{namespace}/list": {
            "get": {
                "description": "find the aim instance status",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "instance"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "identifier of the instance",
                        "name": "namespace",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "max num to display",
                        "name": "max",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "the offset of result",
                        "name": "offset",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ok",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/helm.ReleaseInfo"
                            }
                        }
                    },
                    "404": {
                        "description": "Invalid status not found",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/ex.ApiResponse"
                        }
                    },
                    "500": {
                        "description": "Server Error",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/ex.ApiResponse"
                        }
                    }
                }
            }
        },
        "/instance/namespace/{namespace}/name/{appname}": {
            "put": {
                "description": "Update an Appliation",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "instance"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "namespace of the instance",
                        "name": "namespace",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "identifier of the instance",
                        "name": "appname",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Update instance",
                        "name": "instance",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/helm.ReleaseRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/ex.ApiResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid Name supplied!",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/ex.ApiResponse"
                        }
                    },
                    "404": {
                        "description": "Instance not found",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/ex.ApiResponse"
                        }
                    },
                    "405": {
                        "description": "Invalid input",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/ex.ApiResponse"
                        }
                    },
                    "500": {
                        "description": "Server Error",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/ex.ApiResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "deploy an instance with the givin data",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "instance"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "identifier of the instance",
                        "name": "namespace",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "identifier of the instance",
                        "name": "appname",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "ReleaseRequest of instance",
                        "name": "instance",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/helm.ReleaseRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/ex.ApiResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid Name supplied!",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/ex.ApiResponse"
                        }
                    },
                    "405": {
                        "description": "Invalid input",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/ex.ApiResponse"
                        }
                    },
                    "500": {
                        "description": "Server Error",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/ex.ApiResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete an Appliation",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "instance"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "identifier of the instance",
                        "name": "namespace",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "identifier of the instance",
                        "name": "appname",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/ex.ApiResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid Name supplied!",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/ex.ApiResponse"
                        }
                    },
                    "404": {
                        "description": "Instance not found",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/ex.ApiResponse"
                        }
                    },
                    "500": {
                        "description": "Server Error",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/ex.ApiResponse"
                        }
                    }
                }
            }
        },
        "/instance/namespace/{namespace}/name/{appname}/info": {
            "get": {
                "description": "Get an Appliation by name with status",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "instance"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "identifier of the instance",
                        "name": "namespace",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "identifier of the application",
                        "name": "appname",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ok",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/helm.ReleaseInfo"
                        }
                    },
                    "400": {
                        "description": "Invalid Name supplied!",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/ex.ApiResponse"
                        }
                    },
                    "404": {
                        "description": "Instance not found",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/ex.ApiResponse"
                        }
                    },
                    "405": {
                        "description": "Invalid input",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/ex.ApiResponse"
                        }
                    },
                    "500": {
                        "description": "Server Error",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/ex.ApiResponse"
                        }
                    }
                }
            }
        },
        "/instance/namespace/{namespace}/name/{appname}/version/{version}/rollback": {
            "get": {
                "description": "Rollback Instance to aim version",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "instance"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "identifier of the instance",
                        "name": "namespace",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "identifier of the instance",
                        "name": "appname",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "identifier of the version",
                        "name": "version",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ok",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/ex.ApiResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid Name supplied!",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/ex.ApiResponse"
                        }
                    },
                    "404": {
                        "description": "Instance not found",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/ex.ApiResponse"
                        }
                    },
                    "405": {
                        "description": "Invalid input",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/ex.ApiResponse"
                        }
                    },
                    "500": {
                        "description": "Server Error",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/ex.ApiResponse"
                        }
                    }
                }
            }
        },
        "/pod/{namespace}/{pod}/shell/{container}": {
            "get": {
                "description": "exec shell to prompt with container",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tenant"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "namespace of the pod",
                        "name": "namespace",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "name of the pod",
                        "name": "pod",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "container of the pod",
                        "name": "container",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "shell type to exec",
                        "name": "shell",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ok",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/TerminalResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid Name supplied!",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/ex.ApiResponse"
                        }
                    },
                    "404": {
                        "description": "Instance not found",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/ex.ApiResponse"
                        }
                    },
                    "405": {
                        "description": "Invalid input",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/ex.ApiResponse"
                        }
                    },
                    "500": {
                        "description": "Server Error",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/ex.ApiResponse"
                        }
                    }
                }
            }
        },
        "/tenant": {
            "post": {
                "description": "Create an Tenant with spec info",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tenant"
                ],
                "parameters": [
                    {
                        "description": "Request Info of tenant",
                        "name": "tenant",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/helm.ReleaseRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/ex.ApiResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid Name supplied!",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/ex.ApiResponse"
                        }
                    },
                    "404": {
                        "description": "Instance not found",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/ex.ApiResponse"
                        }
                    },
                    "405": {
                        "description": "Invalid input",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/ex.ApiResponse"
                        }
                    },
                    "500": {
                        "description": "Server Error",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/ex.ApiResponse"
                        }
                    }
                }
            }
        },
        "/tenant/{tenantname}": {
            "get": {
                "description": "Get an Tenant by name",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tenant"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "identifier of the tenant",
                        "name": "tenantname",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ok",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/tenant.TenantInfo"
                        }
                    },
                    "400": {
                        "description": "Invalid Name supplied!",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/ex.ApiResponse"
                        }
                    },
                    "404": {
                        "description": "Instance not found",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/ex.ApiResponse"
                        }
                    },
                    "405": {
                        "description": "Invalid input",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/ex.ApiResponse"
                        }
                    },
                    "500": {
                        "description": "Server Error",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/ex.ApiResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete an Tenant by name",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tenant"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "identifier of the tenant",
                        "name": "tenantname",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ok",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/tenant.TenantInfo"
                        }
                    },
                    "400": {
                        "description": "Invalid Name supplied!",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/ex.ApiResponse"
                        }
                    },
                    "404": {
                        "description": "Instance not found",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/ex.ApiResponse"
                        }
                    },
                    "405": {
                        "description": "Invalid input",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/ex.ApiResponse"
                        }
                    },
                    "500": {
                        "description": "Server Error",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/ex.ApiResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "cluster.Cluster": {
            "type": "object",
            "properties": {
                "apps": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/helm.ReleaseRequest"
                    }
                },
                "configvalues": {
                    "type": "object"
                }
            }
        },
        "cluster.ReleaseList": {
            "type": "object",
            "properties": {
                "apps": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/helm.ReleaseRequest"
                    }
                }
            }
        },
        "ex.ApiResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "helm.ReleaseInfo": {
            "type": "object",
            "properties": {
                "chartappversion": {
                    "type": "string"
                },
                "chartname": {
                    "type": "string"
                },
                "chartversion": {
                    "type": "string"
                },
                "configvalues": {
                    "type": "object"
                },
                "dependencies": {
                    "type": "object"
                },
                "name": {
                    "type": "string"
                },
                "namespace": {
                    "type": "string"
                },
                "statuscode": {
                    "type": "integer"
                },
                "version": {
                    "type": "integer"
                }
            }
        },
        "helm.ReleaseRequest": {
            "type": "object",
            "properties": {
                "chartname": {
                    "type": "string"
                },
                "chartversion": {
                    "type": "string"
                },
                "configvalues": {
                    "type": "object"
                },
                "dependencies": {
                    "type": "object"
                },
                "name": {
                    "type": "string"
                },
                "namespace": {
                    "type": "string"
                }
            }
        },
        "tenant.TenantInfo": {
            "type": "object",
            "properties": {
                "tenant_creation_time": {
                    "type": "string"
                },
                "tenant_labels": {
                    "type": "string"
                },
                "tenant_name": {
                    "type": "string"
                },
                "tenant_status": {
                    "type": "string"
                },
                "tenant_uid": {
                    "type": "string"
                }
            }
        }
    }
}`

type s struct{}

func (s *s) ReadDoc() string {
	return doc
}
func init() {
	swag.Register(swag.Name, &s{})
}
