// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag at
// 2018-06-06 18:36:42.803729036 +0800 CST m=+0.203769945

package docs

import (
	"github.com/swaggo/swag"
)

var doc = `{
    "swagger": "2.0",
    "info": {
        "description": "Warp application lifecycle manager.",
        "title": "Walm",
        "contact": {
            "name": "bing.han",
            "url": "http://transwarp.io",
            "email": "bing.han@transwarp.io"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "http://www.apache.org/licenses/LICENSE-2.0.html"
        },
        "version": "1.0.0"
    },
    "host": "localhost:8000",
    "basePath": "/walm/api/v1",
    "paths": {
        "/instance/{chart}": {
            "put": {
                "description": "Update an Appliation",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "identifier of the chart",
                        "name": "chart",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Update application",
                        "name": "application",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/instance.Application"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/ex.ApiResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid Name supplied!",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/ex.ApiResponse"
                        }
                    },
                    "404": {
                        "description": "Application not found",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/ex.ApiResponse"
                        }
                    },
                    "405": {
                        "description": "Invalid input",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/ex.ApiResponse"
                        }
                    },
                    "500": {
                        "description": "Server Error",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/ex.ApiResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "deploy an application with the givin data",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "identifier of the chart",
                        "name": "chart",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Update application",
                        "name": "application",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/instance.Application"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/ex.ApiResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid Name supplied!",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/ex.ApiResponse"
                        }
                    },
                    "405": {
                        "description": "Invalid input",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/ex.ApiResponse"
                        }
                    },
                    "500": {
                        "description": "Server Error",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/ex.ApiResponse"
                        }
                    }
                }
            }
        },
        "/instance/{namespace}/info/{appname}": {
            "get": {
                "description": "Get an Appliation by name with status",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "identifier of the chart",
                        "name": "namespace",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "identifier of the application",
                        "name": "appname",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ok",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/instance.Info"
                        }
                    },
                    "400": {
                        "description": "Invalid Name supplied!",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/ex.ApiResponse"
                        }
                    },
                    "404": {
                        "description": "Application not found",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/ex.ApiResponse"
                        }
                    },
                    "405": {
                        "description": "Invalid input",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/ex.ApiResponse"
                        }
                    },
                    "500": {
                        "description": "Server Error",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/ex.ApiResponse"
                        }
                    }
                }
            }
        },
        "/instance/{namespace}/rollback/{appname}/{version}": {
            "get": {
                "description": "Rollback Application to aim version",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "identifier of the application",
                        "name": "appname",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "identifier of the version",
                        "name": "version",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "boolean",
                        "description": "if recreate pods",
                        "name": "recreate",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "if force to update and restart pods",
                        "name": "force",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "if wait for finish",
                        "name": "wait",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ok",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/instance.Info"
                        }
                    },
                    "400": {
                        "description": "Invalid Name supplied!",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/ex.ApiResponse"
                        }
                    },
                    "404": {
                        "description": "Application not found",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/ex.ApiResponse"
                        }
                    },
                    "405": {
                        "description": "Invalid input",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/ex.ApiResponse"
                        }
                    },
                    "500": {
                        "description": "Server Error",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/ex.ApiResponse"
                        }
                    }
                }
            }
        },
        "/instance/{namespace}/status/{appname}": {
            "get": {
                "description": "find the aim application status",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "identifier of the chart",
                        "name": "namespace",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "identifier of the appname",
                        "name": "appname",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "boolean",
                        "description": "identifier of the appname",
                        "name": "reverse",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "max num to display",
                        "name": "max",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "the offset of result",
                        "name": "offset",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "if display all of result",
                        "name": "all",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "if display deleted release",
                        "name": "deleted",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "if display deleting release",
                        "name": "deleting",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "if display deployed release",
                        "name": "deployed",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "if display failed release",
                        "name": "failed",
                        "in": "query"
                    },
                    {
                        "type": "boolean",
                        "description": "if display pending release",
                        "name": "pending",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "ok",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/instance.Info"
                        }
                    },
                    "404": {
                        "description": "Invalid status not found",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/ex.ApiResponse"
                        }
                    },
                    "500": {
                        "description": "Server Error",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/ex.ApiResponse"
                        }
                    }
                }
            }
        },
        "/instance/{namespace}/{appname}": {
            "delete": {
                "description": "Delete an Appliation",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "identifier of the application",
                        "name": "appname",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/ex.ApiResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid Name supplied!",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/ex.ApiResponse"
                        }
                    },
                    "404": {
                        "description": "Application not found",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/ex.ApiResponse"
                        }
                    },
                    "500": {
                        "description": "Server Error",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/ex.ApiResponse"
                        }
                    }
                }
            }
        },
        "/{namespace}/{name}": {
            "get": {
                "description": "Get states of an Cluster",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "identifier of the namespace",
                        "name": "namespace",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "the name of cluster",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/ex.ApiResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid Name supplied!",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/ex.ApiResponse"
                        }
                    },
                    "404": {
                        "description": "cluster not found",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/ex.ApiResponse"
                        }
                    },
                    "500": {
                        "description": "Server Error",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/ex.ApiResponse"
                        }
                    }
                }
            },
            "post": {
                "description": "Deplou an Cluster",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "identifier of the namespace",
                        "name": "namespace",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "the name of cluster",
                        "name": "name",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Apps of Cluster",
                        "name": "apps",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/cluster.Cluster"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/ex.ApiResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid Name supplied!",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/ex.ApiResponse"
                        }
                    },
                    "404": {
                        "description": "namespace not found",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/ex.ApiResponse"
                        }
                    },
                    "500": {
                        "description": "Server Error",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/ex.ApiResponse"
                        }
                    }
                }
            },
            "delete": {
                "description": "Delete an Cluster",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "parameters": [
                    {
                        "type": "string",
                        "description": "identifier of the namespace",
                        "name": "namespace",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "the name of cluster",
                        "name": "name",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/ex.ApiResponse"
                        }
                    },
                    "400": {
                        "description": "Invalid Name supplied!",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/ex.ApiResponse"
                        }
                    },
                    "404": {
                        "description": "cluster not found",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/ex.ApiResponse"
                        }
                    },
                    "500": {
                        "description": "Server Error",
                        "schema": {
                            "type": "object",
                            "$ref": "#/definitions/ex.ApiResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "cluster.Cluster": {
            "type": "object",
            "properties": {
                "apps": {
                    "type": "array",
                    "items": {
                        "type": "\u0026{instance Application}"
                    }
                },
                "config": {
                    "type": "string"
                }
            }
        },
        "ex.ApiResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "message": {
                    "type": "string"
                }
            }
        },
        "instance.Application": {
            "type": "object",
            "properties": {
                "install": {
                    "type": "boolean"
                },
                "links": {
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "name": {
                    "type": "string"
                },
                "namespace": {
                    "type": "string"
                },
                "repo": {
                    "type": "string"
                },
                "reset-values": {
                    "type": "boolean"
                },
                "reuse-values": {
                    "type": "boolean"
                },
                "value": {
                    "type": "string"
                },
                "version": {
                    "type": "string"
                }
            }
        },
        "instance.Info": {
            "type": "object",
            "properties": {
                "chart": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "namespace": {
                    "type": "string"
                },
                "revision": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "updated": {
                    "type": "string"
                }
            }
        }
    }
}`

type s struct{}

func (s *s) ReadDoc() string {
	return doc
}
func init() {
	swag.Register(swag.Name, &s{})
}
