== Walm

*Name of project*: Walm

*Description*:

Walm is a micro service, based on link:http://helm.sh[Helm], that supports both Rest Api and Cli to manage the lifecycle of container based applications including those with dependencies.

Walm dynamically manages the dependencies of an application. An application can depend on the applications already existed, and the configurations of applications depending on would be injected automatically. Besides, once the configurations of applications depending on changes, the configurations would be injected again in real-time.

Walm supports more advanced link:https://helm.sh/docs/developing_charts/#charts[Chart] that use link:https://jsonnet.org/[jsonnet] as template engine to render kubernetes objects. It is more suitable to orchestrate and deploy complex applications, such as Big Data applications.

Walm supports finely grained authentication and authorization, that would make one user only have relevant authorization under kubernetes namespace scope.

Walm uses distributed event system to synchronize the application's status in real-time.

*Comparison with similar projects*:
|===
|Walm |Helm

|Walm supports rest api to manage the lifecycle of applications.
|Helm does not support.

|Walm supports the orchestration and deployment of complex applications(jsonnet chart).
|Helm does not support.

|Walm supports the dynamic dependencies management.
|Helm does not support.

|Walm supports the real-time synchronization of the application's status.
|Helm deos not support.

|Walm supports the finely grained authentication and authorization.
|Helm only supports the coarse grained authentication and authorization.

|Walm supports to retrieve the more detailed specification and status of applications.
|Helm only supports to retrieve the basic specification and status of applications.
|===

*Sponsor / Advisor from TOC*: Transwarp

*Unique Identifier*: walm

*License*: ALv2

*Maturity Level:* Incubating

*Source control repositories*:

* https://github.com/WarpCloud/walm
* https://github.com/WarpCloud/walm-charts

*Current Core Maintainers*:

* Yang Cong
* Yu Bian
* Zhiyang Dai
* Lisong Qiu

*Mailing lists*:

* transwarp-community@transwarp.io

*Website*: None

*Infrastructure requirements*: CI, CNCF Cluster, Object Storage

*Issue tracker*: https://github.com/WarpCloud/walm/issues

*Release methodology and mechanics*

Walm uses link:http://semver.org/[semantic versioning] for releases. Releases are announced using GitHub releases while the release artifacts are placed into object storage for later download. The continuous integration systems, currently Jenkins, automatically places releases and development builds into object storage.

*Statement on alignment with CNCF mission*:

Walm support rest api to manage the lifecycle of container based applications and it supports dynamic management of application dependencies.

*External Dependencies*: A full list of dependencies can be found at https://github.com/WarpCloud/walm/blob/master/glide.lock.

*Social media accounts*: N/A

*Adopters*:

* Transwarp

*project logo*: https://github.com/WarpCloud/walm/blob/master/resource/walm_logo.png
